<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#nd-array基础" data-toc-modified-id="nd-array基础-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>nd-array基础</a></span><ul class="toc-item"><li><span><a href="#数组创建" data-toc-modified-id="数组创建-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>数组创建</a></span></li><li><span><a href="#数组结构" data-toc-modified-id="数组结构-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>数组结构</a></span></li><li><span><a href="#数组类型" data-toc-modified-id="数组类型-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>数组类型</a></span></li><li><span><a href="#数组大小" data-toc-modified-id="数组大小-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>数组大小</a></span></li><li><span><a href="#更改数组结构" data-toc-modified-id="更改数组结构-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>更改数组结构</a></span></li></ul></li><li><span><a href="#等距或等比数据" data-toc-modified-id="等距或等比数据-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>等距或等比数据</a></span><ul class="toc-item"><li><span><a href="#np.arange(-)" data-toc-modified-id="np.arange(-)-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>np.arange( )</a></span></li><li><span><a href="#linspace——返回等差数组" data-toc-modified-id="linspace——返回等差数组-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>linspace——返回等差数组</a></span></li><li><span><a href="#logspace——返回等比数列" data-toc-modified-id="logspace——返回等比数列-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>logspace——返回等比数列</a></span></li></ul></li><li><span><a href="#创建特殊数组" data-toc-modified-id="创建特殊数组-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>创建特殊数组</a></span></li><li><span><a href="#生成随机数" data-toc-modified-id="生成随机数-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>生成随机数</a></span></li><li><span><a href="#索引和切片" data-toc-modified-id="索引和切片-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>索引和切片</a></span><ul class="toc-item"><li><span><a href="#一维数组的索引和切片" data-toc-modified-id="一维数组的索引和切片-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>一维数组的索引和切片</a></span></li><li><span><a href="#多维数组的索引和切片" data-toc-modified-id="多维数组的索引和切片-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>多维数组的索引和切片</a></span></li></ul></li><li><span><a href="#数组变形、展平、拼接与分割" data-toc-modified-id="数组变形、展平、拼接与分割-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>数组变形、展平、拼接与分割</a></span><ul class="toc-item"><li><span><a href="#数组的变形" data-toc-modified-id="数组的变形-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>数组的变形</a></span></li><li><span><a href="#数组的展平" data-toc-modified-id="数组的展平-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>数组的展平</a></span></li><li><span><a href="#数组的拼接" data-toc-modified-id="数组的拼接-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>数组的拼接</a></span></li><li><span><a href="#数组分割" data-toc-modified-id="数组分割-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>数组分割</a></span></li></ul></li><li><span><a href="#np.any、np.all" data-toc-modified-id="np.any、np.all-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>np.any、np.all</a></span></li><li><span><a href="#广播" data-toc-modified-id="广播-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>广播</a></span></li><li><span><a href="#排序" data-toc-modified-id="排序-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>排序</a></span></li><li><span><a href="#几个重要函数" data-toc-modified-id="几个重要函数-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>几个重要函数</a></span></li></ul></div>

# Numpy review

In [2]:
import numpy as np
np.__version__

'1.19.2'

## nd-array基础

### 数组创建

In [3]:
# list

li = [1, 'a', 1.34, True]
li

[1, 'a', 1.34, True]

保持同一种数据类型

In [6]:
arr1=np.array([1.,2,3,4])
arr1

dtype('float64')

In [5]:
arr2=np.array([1,'a',3,4])
arr2

array(['1', 'a', '3', '4'], dtype='<U21')

In [10]:
arr3=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,1,2,3]])
print(arr3)
arr3

[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [14]:
arr4=np.array([[[1,2,3,4],[5,6,7,8],[9,1,2,3]],
               [[1,2,3,4],[5,6,7,8],[9,1,2,3]]])
arr4

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 1, 2, 3]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 1, 2, 3]]])

### 数组结构

In [15]:
print(arr3.shape)
print(arr4.shape)

(3, 4)
(2, 3, 4)


### 数组类型

In [17]:
print(arr1.dtype)
print(arr2.dtype)
print(arr4.dtype)

float64
<U21
int64


### 数组大小

In [18]:
arr4.size

24

### 更改数组结构

In [19]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [24]:
arr3.shape=(2,6)
arr3

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 1, 2, 3]])

In [26]:
arr3.reshape((3,4),order='F')

array([[1, 8, 4, 2],
       [7, 3, 1, 6],
       [2, 9, 5, 3]])

In [27]:
arr3.reshape((3,4),order='C')

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

## 等距或等比数据

### np.arange( )

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(3,5,1)

array([3, 4])

In [30]:
np.arange(3,5,0.2)

array([3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [31]:
np.arange(3,5.3,1)

array([3., 4., 5.])

In [34]:
li=[0,1,2,3,4]
print(li)
li2=list(range(5))
print(li2)
li3=np.arange(5)
print(li3)

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[0 1 2 3 4]


###  linspace——返回等差数组

In [36]:
arr5=np.linspace(1,10,31)
arr5

array([ 1. ,  1.3,  1.6,  1.9,  2.2,  2.5,  2.8,  3.1,  3.4,  3.7,  4. ,
        4.3,  4.6,  4.9,  5.2,  5.5,  5.8,  6.1,  6.4,  6.7,  7. ,  7.3,
        7.6,  7.9,  8.2,  8.5,  8.8,  9.1,  9.4,  9.7, 10. ])

In [37]:
arr5.size

31

### logspace——返回等比数列

In [38]:
arr6=np.logspace(1,5,5)
arr6

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [39]:
1.e+01

10.0

In [43]:
arr7=np.logspace(1,6,2,base=2)
arr7

array([ 2., 64.])

In [44]:
np.logspace(1,6,6,base=2)

array([ 2.,  4.,  8., 16., 32., 64.])

## 创建特殊数组

In [45]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
np.diag([2,3,4,6])

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [48]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
np.ones((3,4))*2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

## 生成随机数

In [50]:
np.random.random(10)

array([0.1537138 , 0.99407742, 0.03548637, 0.8079119 , 0.84683644,
       0.83649841, 0.56629879, 0.91720433, 0.79235874, 0.95802923])

In [51]:
np.random.choice(['a','b','c'])

'b'

In [59]:
np.random.choice(['a','b','c'],size=2,replace=True)

array(['b', 'a'], dtype='<U1')

In [60]:
# np.random.choice(['a','b','c'],4,replace=False)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [52]:
np.random.rand(2,3,4)

array([[[0.21033877, 0.06949416, 0.69252146, 0.9306342 ],
        [0.76579435, 0.45737568, 0.22398682, 0.84115382],
        [0.44718971, 0.14827527, 0.67328523, 0.30924022]],

       [[0.85099823, 0.9878969 , 0.64211838, 0.89765968],
        [0.5651743 , 0.51007186, 0.25026747, 0.51510247],
        [0.98201574, 0.07898424, 0.33432964, 0.6026123 ]]])

In [53]:
np.random.randn(2,3)

array([[ 1.68775026,  0.88845982, -0.84042413],
       [ 0.55836987, -0.27686835, -0.1055621 ]])

In [54]:
np.random.randint(2,5,size=(3,4))

array([[3, 4, 4, 3],
       [3, 2, 3, 2],
       [4, 3, 4, 3]])

## 索引和切片

### 一维数组的索引和切片

In [65]:
a1=np.arange(10)
print(a1)
print(a1[4])
print(a1[4:8])
print(a1[4:8].dtype)

[0 1 2 3 4 5 6 7 8 9]
4
[4 5 6 7]
int64


In [71]:
print(a1[-1])
print(a1[3:])
print(a1[3::2])
print(a1[::-2])
print(a1[:])

9
[3 4 5 6 7 8 9]
[3 5 7 9]
[9 7 5 3 1]
[0 1 2 3 4 5 6 7 8 9]


### 多维数组的索引和切片

In [72]:
arr=np.array([
    [1,2,3,4,5],
    [4,5,6,7,8],
    [7,8,9,10,11]
])
arr

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 7,  8,  9, 10, 11]])

In [73]:
arr[0][1]

2

In [77]:
arr[0,1]

2

In [74]:
arr[1][2]

6

In [75]:
arr[1][1:3]

array([5, 6])

In [76]:
arr[1,1:3]

array([5, 6])

In [78]:
arr[1:3,2:4]

array([[ 6,  7],
       [ 9, 10]])

In [79]:
arr[1:,1:]

array([[ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

## 数组变形、展平、拼接与分割

### 数组的变形

In [80]:
a2=np.arange(12)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [81]:
a3=a2.reshape((3,4))
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
a3.ndim

2

### 数组的展平

In [83]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [84]:
a3.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [85]:
a3.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [86]:
a3.flatten(order='F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### 数组的拼接

In [87]:
arr1=np.arange(1,7).reshape((3,2))
arr2=np.arange(11,17).reshape((3,2))
print(arr1)
print(arr2)

[[1 2]
 [3 4]
 [5 6]]
[[11 12]
 [13 14]
 [15 16]]


In [90]:
np.hstack((arr1,arr2))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16]])

In [91]:
np.vstack((arr1,arr2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 12],
       [13, 14],
       [15, 16]])

In [93]:
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 12],
       [13, 14],
       [15, 16]])

In [94]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16]])

### 数组分割

In [95]:
arr11=np.arange(8).reshape((2,4))
arr11

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [96]:
np.hsplit(arr11,2)

[array([[0, 1],
        [4, 5]]),
 array([[2, 3],
        [6, 7]])]

In [97]:
np.vsplit(arr11,2)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]])]

In [98]:
np.split(arr11,2,axis=1)

[array([[0, 1],
        [4, 5]]),
 array([[2, 3],
        [6, 7]])]

In [99]:
np.split(arr11,2,axis=0)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]])]

## np.any、np.all

In [103]:
arr12=np.array([True,True,False])
arr13=np.array([True,True,True])
arr14=np.array([False,False,False])

print(np.any(arr12))
print(np.any(arr14))
print(np.all(arr12))
print(np.all(arr13))

True
False
False
True


## 广播

In [104]:
arr15=np.arange(15).reshape((5,3))
arr15

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [106]:
arr16=np.array([1,2,3])
arr16

array([1, 2, 3])

In [107]:
arr15+arr16

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11],
       [10, 12, 14],
       [13, 15, 17]])

## 排序

In [108]:
arr21=np.array([4,3,2])
np.sort(arr21)

array([2, 3, 4])

In [110]:
arr21.sort()
arr21

array([2, 3, 4])

In [113]:
arr21=np.array([4,3,2])
sorted(arr21)

[2, 3, 4]

In [114]:
np.argsort(arr21)

array([2, 1, 0])

## 几个重要函数

In [115]:
arr22=np.array([3,4,2,1,1,3,2,4])
np.unique(arr22)

array([1, 2, 3, 4])

In [117]:
arr21

array([4, 3, 2])

In [119]:
np.tile(arr21,5)

array([4, 3, 2, 4, 3, 2, 4, 3, 2, 4, 3, 2, 4, 3, 2])

In [120]:
np.repeat(arr21,[4,3,2])

array([4, 4, 4, 4, 3, 3, 3, 2, 2])

In [121]:
arr23=np.arange(6).reshape((2,3))
arr23

array([[0, 1, 2],
       [3, 4, 5]])

In [122]:
np.repeat(arr23,2,axis=1)

array([[0, 0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5, 5]])

In [123]:
np.repeat(arr23,2,axis=0)

array([[0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [3, 4, 5]])

In [126]:
np.tile(arr23,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [127]:
np.tile(arr23,(2,3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5]])

In [128]:
arr23

array([[0, 1, 2],
       [3, 4, 5]])

In [129]:
arr23.sum(axis=0)

array([3, 5, 7])

In [130]:
arr23.mean()

2.5

In [134]:
arr23.std()

1.707825127659933

In [135]:
arr23.var()

2.9166666666666665

In [136]:
arr23.argmax(axis=0)

array([1, 1, 1])

In [138]:
arr23.argmin(axis=1)

array([0, 0])

In [139]:
arr23.cumsum()

array([ 0,  1,  3,  6, 10, 15])