<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#生成数据" data-toc-modified-id="生成数据-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>生成数据</a></span></li><li><span><a href="#集中趋势" data-toc-modified-id="集中趋势-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>集中趋势</a></span><ul class="toc-item"><li><span><a href="#众数" data-toc-modified-id="众数-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>众数</a></span><ul class="toc-item"><li><span><a href="#numpy实现" data-toc-modified-id="numpy实现-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>numpy实现</a></span></li><li><span><a href="#scipy实现" data-toc-modified-id="scipy实现-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>scipy实现</a></span></li></ul></li><li><span><a href="#中位数" data-toc-modified-id="中位数-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>中位数</a></span><ul class="toc-item"><li><span><a href="#函数实现" data-toc-modified-id="函数实现-2.2.1"><span class="toc-item-num">2.2.1&nbsp;&nbsp;</span>函数实现</a></span></li><li><span><a href="#numpy实现" data-toc-modified-id="numpy实现-2.2.2"><span class="toc-item-num">2.2.2&nbsp;&nbsp;</span>numpy实现</a></span></li></ul></li><li><span><a href="#分位数" data-toc-modified-id="分位数-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>分位数</a></span></li><li><span><a href="#均值" data-toc-modified-id="均值-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>均值</a></span></li></ul></li><li><span><a href="#离散程度" data-toc-modified-id="离散程度-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>离散程度</a></span><ul class="toc-item"><li><span><a href="#异众比率" data-toc-modified-id="异众比率-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>异众比率</a></span></li><li><span><a href="#极差" data-toc-modified-id="极差-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>极差</a></span></li><li><span><a href="#方差与标准差" data-toc-modified-id="方差与标准差-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>方差与标准差</a></span></li><li><span><a href="#变异系数" data-toc-modified-id="变异系数-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>变异系数</a></span></li><li><span><a href="#四分位差" data-toc-modified-id="四分位差-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>四分位差</a></span></li></ul></li><li><span><a href="#偏差程度" data-toc-modified-id="偏差程度-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>偏差程度</a></span><ul class="toc-item"><li><span><a href="#z-score" data-toc-modified-id="z-score-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>z-score</a></span></li></ul></li><li><span><a href="#相关程度" data-toc-modified-id="相关程度-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>相关程度</a></span><ul class="toc-item"><li><span><a href="#协方差" data-toc-modified-id="协方差-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>协方差</a></span></li><li><span><a href="#相关系数" data-toc-modified-id="相关系数-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>相关系数</a></span></li></ul></li><li><span><a href="#pandas表格概括性统计描述" data-toc-modified-id="pandas表格概括性统计描述-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>pandas表格概括性统计描述</a></span></li></ul></div>

# 常见描述性统计指标的python实现

## 生成数据 

In [2]:
import numpy as np
import pandas as pd

from scipy import stats

In [3]:
# 使用list创造数据
data1 = [1, 2, 3]
data1

[1, 2, 3]

In [4]:
# 使用ndarray创造一组数据
data2 = np.array([1, 2, 3])
print(data2)
data2

[1 2 3]


array([1, 2, 3])

In [5]:
# 使用pd.Series
data3 = pd.Series([1, 2, 3])
data3

0    1
1    2
2    3
dtype: int64

In [6]:
# 创造服从正态分布的数据
data4 = np.random.normal(0, 10, size=10)
data4

array([ -7.7303349 ,   8.69954573,  -6.48735845, -20.93345921,
        18.77682182,   2.29204973,   0.71633584,   2.4614473 ,
        -6.99842119, -21.77962673])

In [11]:
# 服从均匀分布的分类数据,0-9
data5 = np.random.randint(0, 10, size=10)
data5

array([5, 4, 9, 5, 6, 8, 4, 0, 1, 1])

## 集中趋势

### 众数

#### numpy实现

In [12]:
data5

array([5, 4, 9, 5, 6, 8, 4, 0, 1, 1])

In [13]:
np.bincount(data5)  # 0出现1次，1出现2次……

array([1, 2, 0, 0, 2, 2, 1, 0, 1, 1])

In [15]:
mode = np.argmax(np.bincount(data5))  # 众数
mode

1

#### scipy实现

In [16]:
stats.mode(data5)

ModeResult(mode=array([1]), count=array([2]))

In [18]:
stats.mode([1, 1, 1, 2, 3, 2, 2, 5, 6, 7])

ModeResult(mode=array([1]), count=array([3]))

In [19]:
stats.mode([1, 2, 3])

ModeResult(mode=array([1]), count=array([1]))

In [21]:
stats.mode([1, 1, 1, 2, 3, 2, 2, 5, 6, 7])[0][0]

1

### 中位数

#### 函数实现

In [24]:
def cal_median(nums):
    length = len(nums)
    sorted_num = sorted(nums)
    if length % 2:
        return sorted_num[lenth//2]

    else:
        return (sorted_num[length//2-1]+sorted_num[length//2])/2


cal_median(data5)

4.5

#### numpy实现

In [26]:
np.median(data5)

4.5

### 分位数

In [30]:
np.quantile(data5, q=[0, 0.25, 0.5, 0.75, 1])

array([0.  , 1.75, 4.5 , 5.75, 9.  ])

In [31]:
np.max(data5)

9

### 均值 

In [32]:
np.mean(data4)

-3.0983000063658324

## 离散程度

### 异众比率

In [34]:
stats.mode(data5)

ModeResult(mode=array([1]), count=array([2]))

In [37]:
(len(data5)-stats.mode(data5)[1][0])/len(data5)

0.8

### 极差

In [39]:
np.max(data4)-np.min(data4)

40.556448541420835

In [40]:
np.ptp(data4)

40.556448541420835

### 方差与标准差

In [42]:
np.var(data4, ddof=1)

156.38505635717925

In [43]:
np.std(data4, ddof=1)

12.505401087417358

In [44]:
np.square(np.std(data4, ddof=1))

156.38505635717922

### 变异系数

In [45]:
np.std(data4, ddof=1)/np.mean(data4)

-4.0362137500317905

### 四分位差

In [46]:
np.quantile(data4, q=0.75)-np.quantile(data4, q=0.25)

9.966454373283646

In [47]:
np.quantile(data4, q=[0.25, 0.75])

array([-7.54735647,  2.4190979 ])

## 偏差程度

### z-score

In [49]:
from sklearn.preprocessing import scale

In [74]:
scale(data4)

array([-0.39043878,  0.99445202, -0.28566707, -1.50334311,  1.84387553,
        0.45435788,  0.32153941,  0.46863657, -0.32874505, -1.5746674 ])

In [52]:
(data4-np.mean(data4))/np.std(data4)

array([-0.39043878,  0.99445202, -0.28566707, -1.50334311,  1.84387553,
        0.45435788,  0.32153941,  0.46863657, -0.32874505, -1.5746674 ])

##  相关程度

### 协方差

In [68]:
data = np.array([data4, data5])
np.cov(data)

array([[156.38505636,   7.93383453],
       [  7.93383453,   8.9       ]])

### 相关系数

In [73]:
np.corrcoef(data)

array([[1.       , 0.2126623],
       [0.2126623, 1.       ]])

In [76]:
np.var(data4, ddof=1)

156.38505635717925

## pandas表格概括性统计描述

In [77]:
# 生成数据
table_df = pd.DataFrame({
    '收入': [np.nan, 10008.5, 8550.0, 3331.3, 15920.0],
    '性别': ['男', '女', '女', '男', '女'],
    '年龄': [24, 28, 25, 20, 27],
    '职业': ['公务员', '数据分析师', '审计', '收银员', '数据分析师']
})

table_df

收入 性别  年龄     职业
0      NaN  男  24    公务员
1  10008.5  女  28  数据分析师
2   8550.0  女  25     审计
3   3331.3  男  20    收银员
4  15920.0  女  27  数据分析师

In [78]:
table_df.describe()

收入         年龄
count      4.000000   5.000000
mean    9452.450000  24.800000
std     5177.556951   3.114482
min     3331.300000  20.000000
25%     7245.325000  24.000000
50%     9279.250000  25.000000
75%    11486.375000  27.000000
max    15920.000000  28.000000

In [80]:
# 包括所有变量
table_df.describe(include='all')

收入   性别         年龄     职业
count       4.000000    5   5.000000      5
unique           NaN    2        NaN      4
top              NaN    女        NaN  数据分析师
freq             NaN    3        NaN      2
mean     9452.450000  NaN  24.800000    NaN
std      5177.556951  NaN   3.114482    NaN
min      3331.300000  NaN  20.000000    NaN
25%      7245.325000  NaN  24.000000    NaN
50%      9279.250000  NaN  25.000000    NaN
75%     11486.375000  NaN  27.000000    NaN
max     15920.000000  NaN  28.000000    NaN

In [82]:
table_df.dtypes

收入    float64
性别     object
年龄      int64
职业     object
dtype: object

In [85]:
table_df.describe(include='object')

性别     职业
count   5      5
unique  2      4
top     女  数据分析师
freq    3      2