<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#数据集说明" data-toc-modified-id="数据集说明-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>数据集说明</a></span></li><li><span><a href="#Modelling" data-toc-modified-id="Modelling-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Modelling</a></span></li><li><span><a href="#预测" data-toc-modified-id="预测-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>预测</a></span></li></ul></div>

# Clustering Demo

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams['font.sans-serif'] = ['Arial Unicode MS']
plt.rcParams['axes.unicode_minus'] = False

plt.style.available
style='tableau-colorblind10'
sns.set_style('whitegrid')

## 数据集说明

In [3]:
soccer_df=pd.read_csv('soccer.csv',sep=',',encoding='gb2312')
soccer_df

国家  2019年国际排名  2018世界杯  2015亚洲杯
0       中国         73       40        7
1       日本         60       15        5
2       韩国         61       19        2
3       伊朗         34       18        6
4       沙特         67       26       10
5      伊拉克         91       40        4
6      卡塔尔        101       40       13
7      阿联酋         81       40        6
8   乌兹别克斯坦         88       40        8
9       泰国        122       40       17
10      越南        102       50       17
11      阿曼         87       50       12
12      巴林        116       50       11
13      朝鲜        110       50       14
14      印尼        164       50       17
15      澳洲         40       30        1
16     叙利亚         76       40       17
17      约旦        118       50        9
18     科威特        160       50       15
19    巴勒斯坦         96       50       16

In [7]:
cn_soccer=soccer_df[0:1]
cn_soccer

国家  2019年国际排名  2018世界杯  2015亚洲杯
0  中国         73       40        7

In [9]:
X=soccer_df[['2019年国际排名','2018世界杯','2015亚洲杯']]
X.drop([0],axis=0,inplace=True)
X

/Users/wangzizheng/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


2019年国际排名  2018世界杯  2015亚洲杯
1          60       15        5
2          61       19        2
3          34       18        6
4          67       26       10
5          91       40        4
6         101       40       13
7          81       40        6
8          88       40        8
9         122       40       17
10        102       50       17
11         87       50       12
12        116       50       11
13        110       50       14
14        164       50       17
15         40       30        1
16         76       40       17
17        118       50        9
18        160       50       15
19         96       50       16

## Modelling

In [13]:
from sklearn.cluster import KMeans
kmeans=KMeans(n_clusters=3,
              random_state=42)

kmeans.fit(X)

country_labels=kmeans.labels_
country_labels

array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 2, 0],
      dtype=int32)

In [14]:
country_list=soccer_df['国家'][1:]
country_list

1         日本
2         韩国
3         伊朗
4         沙特
5        伊拉克
6        卡塔尔
7        阿联酋
8     乌兹别克斯坦
9         泰国
10        越南
11        阿曼
12        巴林
13        朝鲜
14        印尼
15        澳洲
16       叙利亚
17        约旦
18       科威特
19      巴勒斯坦
Name: 国家, dtype: object

In [15]:
# 把label和国家对应

def soccer_cate(country_list,country_labels):
    country_dict=dict()
    country_dict[0]=list()
    country_dict[1]=list()
    country_dict[2]=list()
    
    for country,label in zip(country_list,country_labels):
        country_dict[label].append(country)
        
    return country_dict

In [16]:
soccer_cate(country_list,country_labels)

{0: ['伊拉克',
  '卡塔尔',
  '阿联酋',
  '乌兹别克斯坦',
  '泰国',
  '越南',
  '阿曼',
  '巴林',
  '朝鲜',
  '叙利亚',
  '约旦',
  '巴勒斯坦'],
 1: ['日本', '韩国', '伊朗', '沙特', '澳洲'],
 2: ['印尼', '科威特']}

In [17]:
# 每一类的中心
kmeans.cluster_centers_

array([[ 99. ,  45. ,  12. ],
       [ 52.4,  21.6,   4.8],
       [162. ,  50. ,  16. ]])

In [18]:
# 平方和
kmeans.inertia_

4077.2

## 预测

In [19]:
cn_soccer_df = cn_soccer[['2019年国际排名', '2018世界杯', '2015亚洲杯']]
cn_soccer_x = cn_soccer_df.values
cn_soccer_x

array([[73, 40,  7]])

In [20]:
cn_cate = kmeans.predict(cn_soccer_x)
cn_cate

array([0], dtype=int32)